config/routes.rb
Rails.application.routes.draw do
  resources :profesiones
  resources :experiencias_laborales
  resources :informaciones_academicas
  resources :informacion_academicas
  resources :informacion_academica
  resources :experiencia_laboral
  resources :estudios_complementarios
  resources :referencias_personales
  resources :informacion_academica
  resources :profesiones_usuarios
  devise_for :users
  root to: "profesiones#index"

end

app/models/referencias_personale.rb
# == Schema Information
#
# Table name: referencias_personales
#
#  id         :integer          not null, primary key
#  nombre     :string(255)
#  telefono   :string(255)
#  profesion  :string(255)
#  usuario_id :integer
#  created_at :datetime
#  updated_at :datetime
#

class ReferenciasPersonale < ActiveRecord::Base
	belongs_to :usuario
  	
  	validates :nombre, :presence => { :message => "Por Favor ingresa un nombre"}
  	validates_format_of :nombre, :with => /[A-Z]/, :message => "Por Favor ingresa la primera letra en Mayuscula"
	validates_format_of :nombre, :with => /\A[a-zA-Z]+\z/,  :message => "Por favor ingresa solo texto"
	
	validates :profesion, :presence => { :message => "Por Favor ingresa una profesion"}
	

	validates :telefono, :presence => { :message => "Por Favor ingresa un telefono"}
	validates_length_of :telefono, :in => 6..20 , :message => "Por Favor ingresa un telefono valido"

  	def self.search(search)
		where("nombre like '%#{search}%' or telefono like '%#{search}%' 
	    or profesion like '%#{search}%'")
	end
end

app/controllers/referencias_personales_controller.rb
class ReferenciasPersonalesController < ApplicationController
  before_action :set_referencias_personale, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @referencias_personales = ReferenciasPersonale.search(params[:search]).page(params[:page]).per_page(5).where usuario_id: current_user.id    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @referencias_personales }
      end
  end

  def show
    @referencias_personale = ReferenciasPersonale.find(params[:id])
  end

  def new
    @referencias_personale = ReferenciasPersonale.new
  end

  def edit
    @referencias_personale = ReferenciasPersonale.find(params[:id])
  end

  def create
    @referencias_personale = ReferenciasPersonale.new(referencias_personale_params)
    render :action => :new unless @referencias_personale.save
  end

  def update
    @referencias_personale = ReferenciasPersonale.find(params[:id])
    render :action => :edit unless @referencias_personale.update_attributes(referencias_personale_params)
  end


  def destroy
      @referencias_personale = ReferenciasPersonale.find(params[:id])
      @referencias_personale.destroy
  end
  
  private
    def set_referencias_personale
      @referencias_personale = ReferenciasPersonale.find(params[:id])
    end

    def referencias_personale_params
      params.require(:referencias_personale).permit(:nombre, :telefono, :profesion, :usuario_id)
    end
end

app/helpers/referencias_personales_helper.rb
module ReferenciasPersonalesHelper
end

app/views/referencias_personales/_form.html.erb
<%= simple_form_for(@referencias_personale, :html => { :multipart => true, :remote => true }) do |f| %>
<div class="user">
  <div class="modal-header">
    <h4 class="modal-title"><h3>Datos Referencia Personal</h3></h4>
  </div><br>
  <div class="row">
    <div class="col-md-4">
      Nombre:
    </div>
    <div class="col-md-6">
      <%= f.input :nombre, :label => false,  :required => true %>
    </div>
    <div class="col-md-4">
      Telefono:
    </div>
    <div class="col-md-6">
      <%= f.input :telefono, :label => false,  :required => true  %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      Profesión:
    </div>
    <div class="col-md-6">
      <%= f.input :profesion, :label => false,  :required => true %>
    </div>
        <%= f.hidden_field :usuario_id, :value => current_user.id %>
  </div>
</div>
<div class="modal-footer">
  <%= f.submit "Guardar", :class => 'btn btn-primary' %>
  <a href="#" class="btn btn-default" onclick="$.lazybox.close()">Cerrar</a>
</div>
<% end %>

app/views/referencias_personales/_referencias_personale.html.erb
<tr id=<%= "referencias_personale_#{referencias_personale.id}" %>>
    <td><%= link_to referencias_personale.id, edit_referencias_personale_path(referencias_personale), :remote => true %></td>
    <td><%= referencias_personale.nombre %></td>
    <td><%= referencias_personale.telefono %></td>
    <td><%= referencias_personale.profesion %></td>
    <td><%= referencias_personale.usuario_id %></td>    
    <td>
        <%= link_to  image_tag('view1.png'), referencias_personale, :remote => true,  :rel => "tooltip", :title => "Mostrar", :class => 'btn btn-link'%>
        <%= link_to image_tag('editar1.png'), edit_referencias_personale_path(referencias_personale),  :remote => true,  :rel => "tooltip", :title => "Editar", :class => 'btn btn-link'%>
    </td>
</tr>

app/views/referencias_personales/_show.html.erb
<%- model_class = ReferenciasPersonale -%>
<button type="button" class="close" data-dismiss="modal" aria-hidden="true" onclick="$.lazybox.close()">&times;</button>
<div class="page-header">
  <h2>Referencia Personal:<%= @referencias_personale.id %></h2>
  <table class="table table-bordered table-hover" >
    <thead>
      <tr class="info">
        <th>Usuario</th>
        <th>Telefono</th>
        <th>Profesión</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><p><%= @referencias_personale.nombre %></p></td>
        <td><p><%= @referencias_personale.telefono %></p></td>
        <td><p><%= @referencias_personale.profesion %></p></td> 
      </tr>
    </tbody>
  </table>
  <div class="modal-footer">
    <a href="#" class="btn btn-primary" onclick="$.lazybox.close()">Cerrar</a>
  </div>
</div>

app/views/referencias_personales/create.js.erb
$('table tbody').append("<%= escape_javascript(render @referencias_personale) %>")
$.lazybox.close()

app/views/referencias_personales/destroy.js.erb
$("table tr#referencias_personale_<%= @referencias_personale.id %>").remove();

app/views/referencias_personales/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/referencias_personales/index.html.erb
<%- model_class = ProfesionesUsuario -%>
<div class="page-header">
  <h1>Referencias Personales</h1>
</div>

<%= form_tag request.path, :method => 'get' do %>
<%= content_tag :label do %>
Buscar:
<%= text_field_tag :search, params[:search], :placeholder => "Nombre, Telefono, Profesion" %>
<%= submit_tag "Consultar", :name => nil %>
<% end %>
<% end %>
<br />

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Nombre</th>
      <th>Telefono</th>
      <th>Profesion</th>
      <th>Usuario</th>
      <th>Opciones</th>
    </tr>
  </thead>
  <tbody>
   <%= render @referencias_personales %>
  </tbody>
</table>
<%= link_to image_tag('nuevo.png',),  new_referencias_personale_path,  :remote => true, :rel => "tooltip", :title => "Ingresar Nueva Referencia Personal", :class => "btn btn-link " %>

<br />
<br />
<div align="center">
  <%= will_paginate @referencias_personales, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
  &raquo;' %>
</div>
<div align="center">
  Total Referencias Academicas : <%= @referencias_personales.total_entries %>
</div>

app/views/referencias_personales/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/referencias_personales/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})

app/views/referencias_personales/update.js.erb
$('tr#referencias_personale_<%= @referencias_personale.id %>').replaceWith("<%= escape_javascript(render @referencias_personale) %>")
$.lazybox.close()