config/routes.rb
Rails.application.routes.draw do
  resources :profesiones
  resources :experiencias_laborales
  resources :informaciones_academicas
  resources :informacion_academicas
  resources :informacion_academica
  resources :experiencia_laboral
  resources :estudios_complementarios
  resources :referencias_personales
  resources :informacion_academica
  resources :profesiones_usuarios
  devise_for :users
  root to: "profesiones#index"

end

app/models/estudios_complementario.rb
# == Schema Information
#
# Table name: estudios_complementarios
#
#  id                 :integer          not null, primary key
#  nombre             :string(255)
#  entidad            :string(255)
#  fecha_terminacion  :date
#  intensidad_horaria :time
#  usuario_id         :integer
#  created_at         :datetime
#  updated_at         :datetime
#

class EstudiosComplementario < ActiveRecord::Base
  	belongs_to :usuario

  	validates :nombre, :presence => { :message => "Por Favor ingresa un nombre"}
  	validates_format_of :nombre, :with => /[A-Z]/, :message => "Por Favor ingresa la primera letra en Mayuscula"
	validates_format_of :nombre, :with => /\A[a-zA-Z]+\z/,  :message => "Por favor ingresa solo texto"

  	validates :entidad, :presence => { :message => "Por Favor ingresa una entidad"}
  	validates_format_of :entidad, :with => /[A-Z]/, :message => "Por Favor ingresa la primera letra en Mayuscula"
	validates_format_of :entidad, :with => /\A[a-zA-Z]+\z/,  :message => "Por favor ingresa solo texto"

  	validates :intensidad_horaria, :presence => { :message => "Por Favor ingresa una Intensidad Horaria"}

	validates :fecha_terminacion,
  		date: { before: Proc.new { Date.today }, message: "La Fecha debe ser anterior a la fecha actual	" },
  	on: :create

  	def self.search(search)
		where("nombre like '%#{search}%' or entidad like '%#{search}%'")
	end
end

app/controllers/estudios_complementarios_controller.rb
class EstudiosComplementariosController < ApplicationController
  before_action :set_estudios_complementario, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @estudios_complementarios = EstudiosComplementario.search(params[:search]).page(params[:page]).per_page(5).where usuario_id: current_user.id    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @estudios_complementarios }
    end
  end

  def show
    estudios_complementario = EstudiosComplementario.find(params[:id])
  end

  def new
    @estudios_complementario = EstudiosComplementario.new
  end

  def edit
    @estudios_complementario = EstudiosComplementario.find(params[:id])
  end

  def create
    @estudios_complementario = EstudiosComplementario.new(estudios_complementario_params)
    render :action => :new unless @estudios_complementario.save
  end

  def update
    @estudios_complementario = EstudiosComplementario.find(params[:id])
    render :action => :edit unless @estudios_complementario.update_attributes(estudios_complementario_params)
  end

  def destroy
      @estudios_complementario = EstudiosComplementario.find(params[:id])
      @estudios_complementario.destroy
  end

  private
    def set_estudios_complementario
      @estudios_complementario = EstudiosComplementario.find(params[:id])
    end

    def estudios_complementario_params
      params.require(:estudios_complementario).permit(:nombre, :entidad, :fecha_terminacion, :intensidad_horaria, :usuario_id)
    end
end

app/helpers/estudios_complementarios_helper.rb
module EstudiosComplementariosHelper
end

app/views/estudios_complementarios/_estudios_complementario.html.erb
<tr id=<%= "estudios_complementario_#{estudios_complementario.id}" %>>
    <td><%= link_to estudios_complementario.id, edit_estudios_complementario_path(estudios_complementario), :remote => true %></td>
    <td><%= estudios_complementario.nombre %></td>
    <td><%= estudios_complementario.entidad %></td>
    <td><%= estudios_complementario.fecha_terminacion %></td>
    <td><%= estudios_complementario.intensidad_horaria %></td>
    <td><%= estudios_complementario.usuario_id %></td>    
    <td>
        <%= link_to  image_tag('view1.png'), estudios_complementario, :remote => true,  :rel => "tooltip", :title => "Mostrar", :class => 'btn btn-link'%>
        <%= link_to image_tag('editar1.png'), edit_estudios_complementario_path(estudios_complementario),  :remote => true,  :rel => "tooltip", :title => "Editar", :class => 'btn btn-link'%>
    </td>
</tr>

app/views/estudios_complementarios/_form.html.erb
<%= simple_form_for(@estudios_complementario, :html => { :multipart => true, :remote => true }) do |f| %>
<div class="user">
  <div class="modal-header">
    <h4 class="modal-title"><h3>Datos Estudio Complementario</h3></h4>
  </div><br>
  <div class="row">
    <div class="col-md-4">
      Nombre:
    </div>
    <div class="col-md-6">
      <%= f.input :nombre, :label => false,  :required => true %>
    </div>
    <div class="col-md-4">
      Entidad:
    </div>
    <div class="col-md-6">
      <%= f.input :entidad, :label => false,  :required => true  %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      Fecha Terminación:
    </div>
    <div class="col-md-6">
      <%= f.input :fecha_terminacion, :label => false,  :required => true %>
    </div>
    <div class="col-md-4">
      Intensidad Horaria:
    </div>
    <div class="col-md-6">
      <%= f.input :intensidad_horaria, :label => false,  :required => true  %>
    </div>
  </div>
  <%= f.hidden_field :usuario_id, :value => current_user.id %>

</div>
<div class="modal-footer">
  <%= f.submit "Guardar", :class => 'btn btn-primary' %>
  <a href="#" class="btn btn-default" onclick="$.lazybox.close()">Cerrar</a>
</div>
<% end %>

app/views/estudios_complementarios/_show.html.erb
<%- model_class = EstudiosComplementario -%>
<button type="button" class="close" data-dismiss="modal" aria-hidden="true" onclick="$.lazybox.close()">&times;</button>
<div class="page-header">
  <h2>Estudio Complementario:<%= @estudios_complementario.id %></h2>
  <table class="table table-bordered table-hover" >
    <thead>
      <tr class="info">
        <th>Nombre</th>
        <th>Entidad</th>
        <th>Fecha Terminación</th>
        <th>Intensidad Horaria</th>
        <th>Usuario</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><p><%= @estudios_complementario.nombre %></p></td>
        <td><p><%= @estudios_complementario.entidad %></p></td> 
        <td><p><%= @estudios_complementario.fecha_terminacion %></p></td> 
        <td><p><%= @estudios_complementario.intensidad_horaria %></p></td> 
        <td><p><%= @estudios_complementario.usuario_id %></p></td>
      </tr>
    </tbody>
  </table>
  <div class="modal-footer">
    <a href="#" class="btn btn-primary" onclick="$.lazybox.close()">Cerrar</a>
  </div>
</div>

app/views/estudios_complementarios/create.js.erb
$('table tbody').append("<%= escape_javascript(render @estudios_complementario) %>")
$.lazybox.close()

app/views/estudios_complementarios/destroy.js.erb
$("table tr#estudios_complementario_<%= @estudios_complementario.id %>").remove();

app/views/estudios_complementarios/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/estudios_complementarios/index.html.erb
<%- model_class = EstudiosComplementario -%>
<div class="page-header">
  <h1>Estudio Complementario</h1>
</div>

<%= form_tag request.path, :method => 'get' do %>
<%= content_tag :label do %>
Buscar:
<%= text_field_tag :search, params[:search], :placeholder => "Nombre, Entidad" %>
<%= submit_tag "Consultar", :name => nil %>
<% end %>
<% end %>
<br />

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Nombres</th>
      <th>Entidad</th>
      <th>Fecha Terminacion</th>
      <th>Intensidad Horaria</th>
      <th>Usuario</th>
      <th>Opciones</th>
    </tr>
  </thead>
  <tbody>
    <%= render @estudios_complementarios %>
  </tbody>
</table>
<%= link_to image_tag('nuevo.png',),  new_estudios_complementario_path,  :remote => true, :rel => "tooltip", :title => "Ingresar nuevo Estudio Complementario", :class => "btn btn-link " %>

<br />
<br />
<div align="center">
  <%= will_paginate @estudios_complementarios, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
  &raquo;' %>
</div>
<div align="center">
  Total Estudios Complementarios : <%= @estudios_complementarios.total_entries %>
</div>

app/views/estudios_complementarios/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/estudios_complementarios/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})

app/views/estudios_complementarios/update.js.erb
$('tr#estudios_complementario_<%= @estudios_complementario.id %>').replaceWith("<%= escape_javascript(render @estudios_complementario) %>")
$.lazybox.close()