config/routes.rb
Rails.application.routes.draw do
  resources :profesiones
  resources :experiencias_laborales
  resources :informaciones_academicas
  resources :informacion_academicas
  resources :informacion_academica
  resources :experiencia_laboral
  resources :estudios_complementarios
  resources :referencias_personales
  resources :informacion_academica
  resources :profesiones_usuarios
  devise_for :users
  root to: "profesiones#index"

end

app/models/profesiones_usuario.rb
# == Schema Information
#
# Table name: profesiones_usuarios
#
#  id           :integer          not null, primary key
#  usuario_id   :integer
#  profesion_id :integer
#  created_at   :datetime
#  updated_at   :datetime
#

class ProfesionesUsuario < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :profesion
   	validates :usuario_id, :presence => { :message => "Por Favor Selecciona un usuario"}
  	validates :profesion_id, :presence => { :message => "Por Favor Selecciona una profesion"}

    def self.search(search)
		where("")
	end
end

app/controllers/profesiones_usuarios_controller.rb
class ProfesionesUsuariosController < ApplicationController
  before_action :set_profesiones_usuario, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @profesiones_usuarios = ProfesionesUsuario.search(params[:search]).page(params[:page]).per_page(5).where usuario_id: current_user.id    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profesiones_usuarios }
      end
  end
  def show
    @profesiones_usuario = ProfesionesUsuario.find(params[:id])
  end

  def new
    @profesiones_usuario = ProfesionesUsuario.new
  end

  def edit
    @profesiones_usuario = ProfesionesUsuario.find(params[:id])
  end

  def create
    @profesiones_usuario = ProfesionesUsuario.new(profesiones_usuario_params)
    render :action => :new unless @profesiones_usuario.save
  end

  def update
    @profesiones_usuario = ProfesionesUsuario.find(params[:id])
    render :action => :edit unless @profesiones_usuario.update_attributes(profesiones_usuario_params)
  end

  def destroy
    @profesiones_usuario = ProfesionesUsuario.find(params[:id])
    @profesiones_usuario.destroy
  end

  private
    def set_profesiones_usuario
      @profesiones_usuario = ProfesionesUsuario.find(params[:id])
    end

    def profesiones_usuario_params
      params.require(:profesiones_usuario).permit(:usuario_id, :profesion_id)
    end
end

app/helpers/profesiones_usuarios_helper.rb
module ProfesionesUsuariosHelper
end

app/views/profesiones_usuarios/_form.html.erb
<%= simple_form_for(@profesiones_usuario, :html => { :multipart => true, :remote => true }) do |f| %>
<div class="user">
	<div class="modal-header">
		<h4 class="modal-title"><h3>Datos Profesión Usuario</h3></h4>
	</div><br>
	<div class="row">
		<div class="col-md-4">
			Usuario:
		</div>
		<div class="col-md-6">
			<%= f.input :usuario_id, :label => false,  :required => true %>
		</div>
		<div class="col-md-4">
			Profesion:
		</div>
		<div class="col-md-6">
			<%= f.input :profesion_id, :label => false,  :required => true  %>
		</div>
	</div>
</div>
<div class="modal-footer">
	<%= f.submit "Guardar", :class => 'btn btn-primary' %>
	<a href="#" class="btn btn-default" onclick="$.lazybox.close()">Cerrar</a>
</div>
<% end %>

app/views/profesiones_usuarios/_profesiones_usuario.html.erb
<tr id=<%= "profesiones_usuario_#{profesiones_usuario.id}" %>>
	<td><%= link_to profesiones_usuario.id, edit_profesiones_usuario_path(profesiones_usuario), :remote => true %></td>
	<td><%= profesiones_usuario.usuario_id %></td>
	<td><%= profesiones_usuario.profesion_id %></td>    
	<td>
		<%= link_to  image_tag('view1.png'), profesiones_usuario, :remote => true,  :rel => "tooltip", :title => "Mostrar", :class => 'btn btn-link'%>
		<%= link_to image_tag('editar1.png'), edit_profesiones_usuario_path(profesiones_usuario),  :remote => true,  :rel => "tooltip", :title => "Editar", :class => 'btn btn-link'%>
	</td>
</tr>

app/views/profesiones_usuarios/_show.html.erb
<%- model_class = ProfesionesUsuario -%>
<button type="button" class="close" data-dismiss="modal" aria-hidden="true" onclick="$.lazybox.close()">&times;</button>
<div class="page-header">
  <h2>Profesiones Usuarios:<%= @profesiones_usuario.id %></h2>
  <table class="table table-bordered table-hover" >
    <thead>
      <tr class="info">
        <th>Usuario</th>
        <th>Profesion</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><p><%= @profesiones_usuario.usuario_id %></p></td>
        <td><p><%= @profesiones_usuario.profesion_id %></p></td> 
      </tr>
    </tbody>
  </table>
  <div class="modal-footer">
    <a href="#" class="btn btn-primary" onclick="$.lazybox.close()">Cerrar</a>
  </div>
</div>

app/views/profesiones_usuarios/create.js.erb
$('table tbody').append("<%= escape_javascript(render @profesiones_usuario) %>")
$.lazybox.close()

app/views/profesiones_usuarios/destroy.js.erb
$("table tr#profesiones_usuario_<%= @profesiones_usuario.id %>").remove();

app/views/profesiones_usuarios/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/profesiones_usuarios/index.html.erb
<%- model_class = ProfesionesUsuario -%>
<div class="page-header">
  <h1>Profesiones Usuarios</h1>
</div>

<%= form_tag request.path, :method => 'get' do %>
<%= content_tag :label do %>
Buscar:
<%= text_field_tag :search, params[:search], :placeholder => "Buscador Profesiones Usuarios" %>
<%= submit_tag "Consultar", :name => nil %>
<% end %>
<% end %>
<br />

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>usuario_id</th>
      <th>profesion_id</th>
      <th>Opciones</th>
    </tr>
  </thead>
  <tbody>
   <%= render @profesiones_usuarios %>
 </tbody>
</table>
<%= link_to image_tag('nuevo.png',),  new_profesiones_usuario_path,  :remote => true, :rel => "tooltip", :title => "Ingresar Nueva Profesion Usuario", :class => "btn btn-link " %>

<br />
<br />
<div align="center">
  <%= will_paginate @profesiones_usuarios, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
  &raquo;' %>
</div>
<div align="center">
  Total Profesiones Usuarios : <%= @profesiones_usuarios.total_entries %>
</div>

app/views/profesiones_usuarios/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/profesiones_usuarios/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})

app/views/profesiones_usuarios/update.js.erb
$('tr#profesiones_usuario_<%= @profesiones_usuario.id %>').replaceWith("<%= escape_javascript(render @profesiones_usuario) %>")
$.lazybox.close()